/**
 * generated by Xtext 2.12.0
 */
package co.edu.icesi.eketal.eketal;

import jbase.jbase.XJJvmFormalParameter;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Automaton</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.icesi.eketal.eketal.Automaton#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.icesi.eketal.eketal.Automaton#getParams <em>Params</em>}</li>
 *   <li>{@link co.edu.icesi.eketal.eketal.Automaton#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getAutomaton()
 * @model
 * @generated
 */
public interface Automaton extends Decl
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getAutomaton_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.Automaton#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link jbase.jbase.XJJvmFormalParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getAutomaton_Params()
   * @model containment="true"
   * @generated
   */
  EList<XJJvmFormalParameter> getParams();

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link co.edu.icesi.eketal.eketal.Step}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Steps</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getAutomaton_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // Automaton
