/**
 * generated by Xtext 2.12.0
 */
package co.edu.icesi.eketal.eketal;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.icesi.eketal.eketal.EketalFactory
 * @model kind="package"
 * @generated
 */
public interface EketalPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "eketal";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.icesi.edu.co/eketal/Eketal";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "eketal";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EketalPackage eINSTANCE = co.edu.icesi.eketal.eketal.impl.EketalPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.ModelImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Import Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__IMPORT_SECTION = 1;

  /**
   * The feature id for the '<em><b>Type Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TYPE_DECLARATION = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.EventClassImpl <em>Event Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.EventClassImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEventClass()
   * @generated
   */
  int EVENT_CLASS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_CLASS__NAME = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_CLASS__DECLARATIONS = 1;

  /**
   * The number of structural features of the '<em>Event Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_CLASS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.DeclImpl <em>Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.DeclImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getDecl()
   * @generated
   */
  int DECL = 2;

  /**
   * The number of structural features of the '<em>Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.JVarDImpl <em>JVar D</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.JVarDImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getJVarD()
   * @generated
   */
  int JVAR_D = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVAR_D__NAME = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVAR_D__TYPE = DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>JVar D</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVAR_D_FEATURE_COUNT = DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.MSigImpl <em>MSig</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.MSigImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getMSig()
   * @generated
   */
  int MSIG = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__NAME = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__PARAMS = DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__TYPE = DECL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG__BODY = DECL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>MSig</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MSIG_FEATURE_COUNT = DECL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.EvDeclImpl <em>Ev Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.EvDeclImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEvDecl()
   * @generated
   */
  int EV_DECL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EV_DECL__NAME = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EV_DECL__PARAMS = DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Eventos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EV_DECL__EVENTOS = DECL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Ev Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EV_DECL_FEATURE_COUNT = DECL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.EventExpressionImpl <em>Event Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.EventExpressionImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEventExpression()
   * @generated
   */
  int EVENT_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Tipo Evento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXPRESSION__TIPO_EVENTO = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXPRESSION__OP = 1;

  /**
   * The number of structural features of the '<em>Event Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.EventPredicateImpl <em>Event Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.EventPredicateImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEventPredicate()
   * @generated
   */
  int EVENT_PREDICATE = 7;

  /**
   * The number of structural features of the '<em>Event Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_PREDICATE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.KindAttributeImpl <em>Kind Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.KindAttributeImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getKindAttribute()
   * @generated
   */
  int KIND_ATTRIBUTE = 8;

  /**
   * The feature id for the '<em><b>Hostgroup</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_ATTRIBUTE__HOSTGROUP = EVENT_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ongroup</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_ATTRIBUTE__ONGROUP = EVENT_PREDICATE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_ATTRIBUTE__CONDITION = EVENT_PREDICATE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Kind Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KIND_ATTRIBUTE_FEATURE_COUNT = EVENT_PREDICATE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.TriggerImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 9;

  /**
   * The feature id for the '<em><b>Trigger Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__TRIGGER_TYPE = EVENT_PREDICATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Returndef</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__RETURNDEF = EVENT_PREDICATE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Esig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__ESIG = EVENT_PREDICATE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__PARAMS = EVENT_PREDICATE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = EVENT_PREDICATE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.JVMTYPEImpl <em>JVMTYPE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.JVMTYPEImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getJVMTYPE()
   * @generated
   */
  int JVMTYPE = 10;

  /**
   * The feature id for the '<em><b>Astk</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVMTYPE__ASTK = 0;

  /**
   * The feature id for the '<em><b>Jvm Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVMTYPE__JVM_REF = 1;

  /**
   * The number of structural features of the '<em>JVMTYPE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JVMTYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.GroupImpl <em>Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.GroupImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getGroup()
   * @generated
   */
  int GROUP = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP__NAME = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Hosts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP__HOSTS = DECL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_FEATURE_COUNT = DECL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.HostImpl <em>Host</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.HostImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getHost()
   * @generated
   */
  int HOST = 12;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOST__IP = 0;

  /**
   * The feature id for the '<em><b>Group Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOST__GROUP_ID = 1;

  /**
   * The number of structural features of the '<em>Host</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.AutomatonImpl <em>Automaton</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.AutomatonImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getAutomaton()
   * @generated
   */
  int AUTOMATON = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON__NAME = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON__PARAMS = DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON__STEPS = DECL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Automaton</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTOMATON_FEATURE_COUNT = DECL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.StepImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getStep()
   * @generated
   */
  int STEP = 14;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__NAME = 1;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__TRANSITIONS = 2;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.TransDefImpl <em>Trans Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.TransDefImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getTransDef()
   * @generated
   */
  int TRANS_DEF = 15;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANS_DEF__EVENT = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANS_DEF__TARGET = 1;

  /**
   * The number of structural features of the '<em>Trans Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANS_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.LtlImpl <em>Ltl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.LtlImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtl()
   * @generated
   */
  int LTL = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL__NAME = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL__PARAMS = DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL__PREDICATE = DECL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Ltl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_FEATURE_COUNT = DECL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.LtlExpressionImpl <em>Ltl Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.LtlExpressionImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlExpression()
   * @generated
   */
  int LTL_EXPRESSION = 17;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_EXPRESSION__EVENT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_EXPRESSION__OP = 1;

  /**
   * The number of structural features of the '<em>Ltl Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.RcImpl <em>Rc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.RcImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getRc()
   * @generated
   */
  int RC = 18;

  /**
   * The feature id for the '<em><b>Syncex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RC__SYNCEX = DECL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Pos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RC__POS = DECL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Automaton</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RC__AUTOMATON = DECL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RC__STATE = DECL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RC__BODY = DECL_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Rc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RC_FEATURE_COUNT = DECL_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.BodyImpl <em>Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.BodyImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getBody()
   * @generated
   */
  int BODY = 19;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY__BODY = 0;

  /**
   * The number of structural features of the '<em>Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.OrEventImpl <em>Or Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.OrEventImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getOrEvent()
   * @generated
   */
  int OR_EVENT = 20;

  /**
   * The feature id for the '<em><b>Tipo Evento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__TIPO_EVENTO = EVENT_EXPRESSION__TIPO_EVENTO;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__OP = EVENT_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__LEFT = EVENT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT__RIGHT = EVENT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EVENT_FEATURE_COUNT = EVENT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.AndEventImpl <em>And Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.AndEventImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getAndEvent()
   * @generated
   */
  int AND_EVENT = 21;

  /**
   * The feature id for the '<em><b>Tipo Evento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__TIPO_EVENTO = EVENT_EXPRESSION__TIPO_EVENTO;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__OP = EVENT_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__LEFT = EVENT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT__RIGHT = EVENT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EVENT_FEATURE_COUNT = EVENT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.UnaryEventImpl <em>Unary Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.UnaryEventImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getUnaryEvent()
   * @generated
   */
  int UNARY_EVENT = 22;

  /**
   * The feature id for the '<em><b>Tipo Evento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT__TIPO_EVENTO = EVENT_EXPRESSION__TIPO_EVENTO;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT__OP = EVENT_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT__EXPR = EVENT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Unary Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EVENT_FEATURE_COUNT = EVENT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.LtlThenImpl <em>Ltl Then</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.LtlThenImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlThen()
   * @generated
   */
  int LTL_THEN = 23;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_THEN__EVENT = LTL_EXPRESSION__EVENT;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_THEN__OP = LTL_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_THEN__LEFT = LTL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_THEN__RIGHT = LTL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ltl Then</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_THEN_FEATURE_COUNT = LTL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.LtlOrImpl <em>Ltl Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.LtlOrImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlOr()
   * @generated
   */
  int LTL_OR = 24;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_OR__EVENT = LTL_EXPRESSION__EVENT;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_OR__OP = LTL_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_OR__LEFT = LTL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_OR__RIGHT = LTL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ltl Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_OR_FEATURE_COUNT = LTL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.LtlAndImpl <em>Ltl And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.LtlAndImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlAnd()
   * @generated
   */
  int LTL_AND = 25;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_AND__EVENT = LTL_EXPRESSION__EVENT;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_AND__OP = LTL_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_AND__LEFT = LTL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_AND__RIGHT = LTL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ltl And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_AND_FEATURE_COUNT = LTL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.LtlUntilImpl <em>Ltl Until</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.LtlUntilImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlUntil()
   * @generated
   */
  int LTL_UNTIL = 26;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_UNTIL__EVENT = LTL_EXPRESSION__EVENT;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_UNTIL__OP = LTL_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_UNTIL__LEFT = LTL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_UNTIL__RIGHT = LTL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ltl Until</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTL_UNTIL_FEATURE_COUNT = LTL_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.impl.UnaryLtlImpl <em>Unary Ltl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.impl.UnaryLtlImpl
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getUnaryLtl()
   * @generated
   */
  int UNARY_LTL = 27;

  /**
   * The feature id for the '<em><b>Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_LTL__EVENT = LTL_EXPRESSION__EVENT;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_LTL__OP = LTL_EXPRESSION__OP;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_LTL__EXPR = LTL_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Unary Ltl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_LTL_FEATURE_COUNT = LTL_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.TPrefix <em>TPrefix</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.TPrefix
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getTPrefix()
   * @generated
   */
  int TPREFIX = 28;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.StateType <em>State Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.StateType
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getStateType()
   * @generated
   */
  int STATE_TYPE = 29;

  /**
   * The meta object id for the '{@link co.edu.icesi.eketal.eketal.Pos <em>Pos</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.icesi.eketal.eketal.Pos
   * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getPos()
   * @generated
   */
  int POS = 30;


  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see co.edu.icesi.eketal.eketal.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.Model#getImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Section</em>'.
   * @see co.edu.icesi.eketal.eketal.Model#getImportSection()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ImportSection();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.Model#getTypeDeclaration <em>Type Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Declaration</em>'.
   * @see co.edu.icesi.eketal.eketal.Model#getTypeDeclaration()
   * @see #getModel()
   * @generated
   */
  EReference getModel_TypeDeclaration();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.EventClass <em>Event Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Class</em>'.
   * @see co.edu.icesi.eketal.eketal.EventClass
   * @generated
   */
  EClass getEventClass();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.EventClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.EventClass#getName()
   * @see #getEventClass()
   * @generated
   */
  EAttribute getEventClass_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.EventClass#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see co.edu.icesi.eketal.eketal.EventClass#getDeclarations()
   * @see #getEventClass()
   * @generated
   */
  EReference getEventClass_Declarations();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Decl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decl</em>'.
   * @see co.edu.icesi.eketal.eketal.Decl
   * @generated
   */
  EClass getDecl();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.JVarD <em>JVar D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JVar D</em>'.
   * @see co.edu.icesi.eketal.eketal.JVarD
   * @generated
   */
  EClass getJVarD();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.JVarD#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.JVarD#getName()
   * @see #getJVarD()
   * @generated
   */
  EAttribute getJVarD_Name();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.JVarD#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see co.edu.icesi.eketal.eketal.JVarD#getType()
   * @see #getJVarD()
   * @generated
   */
  EReference getJVarD_Type();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.MSig <em>MSig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MSig</em>'.
   * @see co.edu.icesi.eketal.eketal.MSig
   * @generated
   */
  EClass getMSig();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.MSig#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.MSig#getName()
   * @see #getMSig()
   * @generated
   */
  EAttribute getMSig_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.MSig#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.icesi.eketal.eketal.MSig#getParams()
   * @see #getMSig()
   * @generated
   */
  EReference getMSig_Params();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.MSig#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see co.edu.icesi.eketal.eketal.MSig#getType()
   * @see #getMSig()
   * @generated
   */
  EReference getMSig_Type();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.MSig#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see co.edu.icesi.eketal.eketal.MSig#getBody()
   * @see #getMSig()
   * @generated
   */
  EReference getMSig_Body();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.EvDecl <em>Ev Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ev Decl</em>'.
   * @see co.edu.icesi.eketal.eketal.EvDecl
   * @generated
   */
  EClass getEvDecl();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.EvDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.EvDecl#getName()
   * @see #getEvDecl()
   * @generated
   */
  EAttribute getEvDecl_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.EvDecl#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.icesi.eketal.eketal.EvDecl#getParams()
   * @see #getEvDecl()
   * @generated
   */
  EReference getEvDecl_Params();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.EvDecl#getEventos <em>Eventos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Eventos</em>'.
   * @see co.edu.icesi.eketal.eketal.EvDecl#getEventos()
   * @see #getEvDecl()
   * @generated
   */
  EReference getEvDecl_Eventos();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.EventExpression <em>Event Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Expression</em>'.
   * @see co.edu.icesi.eketal.eketal.EventExpression
   * @generated
   */
  EClass getEventExpression();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.EventExpression#getTipoEvento <em>Tipo Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tipo Evento</em>'.
   * @see co.edu.icesi.eketal.eketal.EventExpression#getTipoEvento()
   * @see #getEventExpression()
   * @generated
   */
  EReference getEventExpression_TipoEvento();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.EventExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see co.edu.icesi.eketal.eketal.EventExpression#getOp()
   * @see #getEventExpression()
   * @generated
   */
  EAttribute getEventExpression_Op();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.EventPredicate <em>Event Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Predicate</em>'.
   * @see co.edu.icesi.eketal.eketal.EventPredicate
   * @generated
   */
  EClass getEventPredicate();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.KindAttribute <em>Kind Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kind Attribute</em>'.
   * @see co.edu.icesi.eketal.eketal.KindAttribute
   * @generated
   */
  EClass getKindAttribute();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.KindAttribute#getHostgroup <em>Hostgroup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Hostgroup</em>'.
   * @see co.edu.icesi.eketal.eketal.KindAttribute#getHostgroup()
   * @see #getKindAttribute()
   * @generated
   */
  EReference getKindAttribute_Hostgroup();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.KindAttribute#getOngroup <em>Ongroup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ongroup</em>'.
   * @see co.edu.icesi.eketal.eketal.KindAttribute#getOngroup()
   * @see #getKindAttribute()
   * @generated
   */
  EReference getKindAttribute_Ongroup();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.KindAttribute#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see co.edu.icesi.eketal.eketal.KindAttribute#getCondition()
   * @see #getKindAttribute()
   * @generated
   */
  EReference getKindAttribute_Condition();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see co.edu.icesi.eketal.eketal.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Trigger#getTriggerType <em>Trigger Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trigger Type</em>'.
   * @see co.edu.icesi.eketal.eketal.Trigger#getTriggerType()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_TriggerType();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.Trigger#getReturndef <em>Returndef</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Returndef</em>'.
   * @see co.edu.icesi.eketal.eketal.Trigger#getReturndef()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Returndef();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Trigger#getEsig <em>Esig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Esig</em>'.
   * @see co.edu.icesi.eketal.eketal.Trigger#getEsig()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Esig();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.Trigger#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.icesi.eketal.eketal.Trigger#getParams()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_Params();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.JVMTYPE <em>JVMTYPE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>JVMTYPE</em>'.
   * @see co.edu.icesi.eketal.eketal.JVMTYPE
   * @generated
   */
  EClass getJVMTYPE();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.JVMTYPE#getAstk <em>Astk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Astk</em>'.
   * @see co.edu.icesi.eketal.eketal.JVMTYPE#getAstk()
   * @see #getJVMTYPE()
   * @generated
   */
  EAttribute getJVMTYPE_Astk();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.JVMTYPE#getJvmRef <em>Jvm Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Jvm Ref</em>'.
   * @see co.edu.icesi.eketal.eketal.JVMTYPE#getJvmRef()
   * @see #getJVMTYPE()
   * @generated
   */
  EReference getJVMTYPE_JvmRef();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Group <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group</em>'.
   * @see co.edu.icesi.eketal.eketal.Group
   * @generated
   */
  EClass getGroup();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Group#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.Group#getName()
   * @see #getGroup()
   * @generated
   */
  EAttribute getGroup_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.Group#getHosts <em>Hosts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hosts</em>'.
   * @see co.edu.icesi.eketal.eketal.Group#getHosts()
   * @see #getGroup()
   * @generated
   */
  EReference getGroup_Hosts();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Host <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Host</em>'.
   * @see co.edu.icesi.eketal.eketal.Host
   * @generated
   */
  EClass getHost();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Host#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip</em>'.
   * @see co.edu.icesi.eketal.eketal.Host#getIp()
   * @see #getHost()
   * @generated
   */
  EAttribute getHost_Ip();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.Host#getGroupId <em>Group Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Group Id</em>'.
   * @see co.edu.icesi.eketal.eketal.Host#getGroupId()
   * @see #getHost()
   * @generated
   */
  EReference getHost_GroupId();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Automaton <em>Automaton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Automaton</em>'.
   * @see co.edu.icesi.eketal.eketal.Automaton
   * @generated
   */
  EClass getAutomaton();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Automaton#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.Automaton#getName()
   * @see #getAutomaton()
   * @generated
   */
  EAttribute getAutomaton_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.Automaton#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.icesi.eketal.eketal.Automaton#getParams()
   * @see #getAutomaton()
   * @generated
   */
  EReference getAutomaton_Params();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.Automaton#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Steps</em>'.
   * @see co.edu.icesi.eketal.eketal.Automaton#getSteps()
   * @see #getAutomaton()
   * @generated
   */
  EReference getAutomaton_Steps();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see co.edu.icesi.eketal.eketal.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Step#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see co.edu.icesi.eketal.eketal.Step#getType()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Type();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Step#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.Step#getName()
   * @see #getStep()
   * @generated
   */
  EAttribute getStep_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.Step#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see co.edu.icesi.eketal.eketal.Step#getTransitions()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Transitions();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.TransDef <em>Trans Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trans Def</em>'.
   * @see co.edu.icesi.eketal.eketal.TransDef
   * @generated
   */
  EClass getTransDef();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.TransDef#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see co.edu.icesi.eketal.eketal.TransDef#getEvent()
   * @see #getTransDef()
   * @generated
   */
  EReference getTransDef_Event();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.TransDef#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see co.edu.icesi.eketal.eketal.TransDef#getTarget()
   * @see #getTransDef()
   * @generated
   */
  EReference getTransDef_Target();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Ltl <em>Ltl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ltl</em>'.
   * @see co.edu.icesi.eketal.eketal.Ltl
   * @generated
   */
  EClass getLtl();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Ltl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co.edu.icesi.eketal.eketal.Ltl#getName()
   * @see #getLtl()
   * @generated
   */
  EAttribute getLtl_Name();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.icesi.eketal.eketal.Ltl#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see co.edu.icesi.eketal.eketal.Ltl#getParams()
   * @see #getLtl()
   * @generated
   */
  EReference getLtl_Params();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.Ltl#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see co.edu.icesi.eketal.eketal.Ltl#getPredicate()
   * @see #getLtl()
   * @generated
   */
  EReference getLtl_Predicate();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.LtlExpression <em>Ltl Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ltl Expression</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlExpression
   * @generated
   */
  EClass getLtlExpression();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.LtlExpression#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Event</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlExpression#getEvent()
   * @see #getLtlExpression()
   * @generated
   */
  EReference getLtlExpression_Event();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.LtlExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlExpression#getOp()
   * @see #getLtlExpression()
   * @generated
   */
  EAttribute getLtlExpression_Op();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Rc <em>Rc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rc</em>'.
   * @see co.edu.icesi.eketal.eketal.Rc
   * @generated
   */
  EClass getRc();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Rc#getSyncex <em>Syncex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Syncex</em>'.
   * @see co.edu.icesi.eketal.eketal.Rc#getSyncex()
   * @see #getRc()
   * @generated
   */
  EAttribute getRc_Syncex();

  /**
   * Returns the meta object for the attribute '{@link co.edu.icesi.eketal.eketal.Rc#getPos <em>Pos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pos</em>'.
   * @see co.edu.icesi.eketal.eketal.Rc#getPos()
   * @see #getRc()
   * @generated
   */
  EAttribute getRc_Pos();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.Rc#getAutomaton <em>Automaton</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Automaton</em>'.
   * @see co.edu.icesi.eketal.eketal.Rc#getAutomaton()
   * @see #getRc()
   * @generated
   */
  EReference getRc_Automaton();

  /**
   * Returns the meta object for the reference '{@link co.edu.icesi.eketal.eketal.Rc#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see co.edu.icesi.eketal.eketal.Rc#getState()
   * @see #getRc()
   * @generated
   */
  EReference getRc_State();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.Rc#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see co.edu.icesi.eketal.eketal.Rc#getBody()
   * @see #getRc()
   * @generated
   */
  EReference getRc_Body();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.Body <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body</em>'.
   * @see co.edu.icesi.eketal.eketal.Body
   * @generated
   */
  EClass getBody();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.Body#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see co.edu.icesi.eketal.eketal.Body#getBody()
   * @see #getBody()
   * @generated
   */
  EReference getBody_Body();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.OrEvent <em>Or Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Event</em>'.
   * @see co.edu.icesi.eketal.eketal.OrEvent
   * @generated
   */
  EClass getOrEvent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.OrEvent#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.icesi.eketal.eketal.OrEvent#getLeft()
   * @see #getOrEvent()
   * @generated
   */
  EReference getOrEvent_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.OrEvent#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.icesi.eketal.eketal.OrEvent#getRight()
   * @see #getOrEvent()
   * @generated
   */
  EReference getOrEvent_Right();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.AndEvent <em>And Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Event</em>'.
   * @see co.edu.icesi.eketal.eketal.AndEvent
   * @generated
   */
  EClass getAndEvent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.AndEvent#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.icesi.eketal.eketal.AndEvent#getLeft()
   * @see #getAndEvent()
   * @generated
   */
  EReference getAndEvent_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.AndEvent#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.icesi.eketal.eketal.AndEvent#getRight()
   * @see #getAndEvent()
   * @generated
   */
  EReference getAndEvent_Right();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.UnaryEvent <em>Unary Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Event</em>'.
   * @see co.edu.icesi.eketal.eketal.UnaryEvent
   * @generated
   */
  EClass getUnaryEvent();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.UnaryEvent#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see co.edu.icesi.eketal.eketal.UnaryEvent#getExpr()
   * @see #getUnaryEvent()
   * @generated
   */
  EReference getUnaryEvent_Expr();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.LtlThen <em>Ltl Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ltl Then</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlThen
   * @generated
   */
  EClass getLtlThen();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlThen#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlThen#getLeft()
   * @see #getLtlThen()
   * @generated
   */
  EReference getLtlThen_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlThen#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlThen#getRight()
   * @see #getLtlThen()
   * @generated
   */
  EReference getLtlThen_Right();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.LtlOr <em>Ltl Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ltl Or</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlOr
   * @generated
   */
  EClass getLtlOr();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlOr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlOr#getLeft()
   * @see #getLtlOr()
   * @generated
   */
  EReference getLtlOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlOr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlOr#getRight()
   * @see #getLtlOr()
   * @generated
   */
  EReference getLtlOr_Right();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.LtlAnd <em>Ltl And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ltl And</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlAnd
   * @generated
   */
  EClass getLtlAnd();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlAnd#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlAnd#getLeft()
   * @see #getLtlAnd()
   * @generated
   */
  EReference getLtlAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlAnd#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlAnd#getRight()
   * @see #getLtlAnd()
   * @generated
   */
  EReference getLtlAnd_Right();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.LtlUntil <em>Ltl Until</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ltl Until</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlUntil
   * @generated
   */
  EClass getLtlUntil();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlUntil#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlUntil#getLeft()
   * @see #getLtlUntil()
   * @generated
   */
  EReference getLtlUntil_Left();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.LtlUntil#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see co.edu.icesi.eketal.eketal.LtlUntil#getRight()
   * @see #getLtlUntil()
   * @generated
   */
  EReference getLtlUntil_Right();

  /**
   * Returns the meta object for class '{@link co.edu.icesi.eketal.eketal.UnaryLtl <em>Unary Ltl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Ltl</em>'.
   * @see co.edu.icesi.eketal.eketal.UnaryLtl
   * @generated
   */
  EClass getUnaryLtl();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.icesi.eketal.eketal.UnaryLtl#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see co.edu.icesi.eketal.eketal.UnaryLtl#getExpr()
   * @see #getUnaryLtl()
   * @generated
   */
  EReference getUnaryLtl_Expr();

  /**
   * Returns the meta object for enum '{@link co.edu.icesi.eketal.eketal.TPrefix <em>TPrefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>TPrefix</em>'.
   * @see co.edu.icesi.eketal.eketal.TPrefix
   * @generated
   */
  EEnum getTPrefix();

  /**
   * Returns the meta object for enum '{@link co.edu.icesi.eketal.eketal.StateType <em>State Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>State Type</em>'.
   * @see co.edu.icesi.eketal.eketal.StateType
   * @generated
   */
  EEnum getStateType();

  /**
   * Returns the meta object for enum '{@link co.edu.icesi.eketal.eketal.Pos <em>Pos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Pos</em>'.
   * @see co.edu.icesi.eketal.eketal.Pos
   * @generated
   */
  EEnum getPos();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EketalFactory getEketalFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.ModelImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Import Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__IMPORT_SECTION = eINSTANCE.getModel_ImportSection();

    /**
     * The meta object literal for the '<em><b>Type Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TYPE_DECLARATION = eINSTANCE.getModel_TypeDeclaration();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.EventClassImpl <em>Event Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.EventClassImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEventClass()
     * @generated
     */
    EClass EVENT_CLASS = eINSTANCE.getEventClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_CLASS__NAME = eINSTANCE.getEventClass_Name();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_CLASS__DECLARATIONS = eINSTANCE.getEventClass_Declarations();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.DeclImpl <em>Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.DeclImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getDecl()
     * @generated
     */
    EClass DECL = eINSTANCE.getDecl();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.JVarDImpl <em>JVar D</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.JVarDImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getJVarD()
     * @generated
     */
    EClass JVAR_D = eINSTANCE.getJVarD();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JVAR_D__NAME = eINSTANCE.getJVarD_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JVAR_D__TYPE = eINSTANCE.getJVarD_Type();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.MSigImpl <em>MSig</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.MSigImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getMSig()
     * @generated
     */
    EClass MSIG = eINSTANCE.getMSig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MSIG__NAME = eINSTANCE.getMSig_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MSIG__PARAMS = eINSTANCE.getMSig_Params();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MSIG__TYPE = eINSTANCE.getMSig_Type();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MSIG__BODY = eINSTANCE.getMSig_Body();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.EvDeclImpl <em>Ev Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.EvDeclImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEvDecl()
     * @generated
     */
    EClass EV_DECL = eINSTANCE.getEvDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EV_DECL__NAME = eINSTANCE.getEvDecl_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EV_DECL__PARAMS = eINSTANCE.getEvDecl_Params();

    /**
     * The meta object literal for the '<em><b>Eventos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EV_DECL__EVENTOS = eINSTANCE.getEvDecl_Eventos();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.EventExpressionImpl <em>Event Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.EventExpressionImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEventExpression()
     * @generated
     */
    EClass EVENT_EXPRESSION = eINSTANCE.getEventExpression();

    /**
     * The meta object literal for the '<em><b>Tipo Evento</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_EXPRESSION__TIPO_EVENTO = eINSTANCE.getEventExpression_TipoEvento();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_EXPRESSION__OP = eINSTANCE.getEventExpression_Op();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.EventPredicateImpl <em>Event Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.EventPredicateImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getEventPredicate()
     * @generated
     */
    EClass EVENT_PREDICATE = eINSTANCE.getEventPredicate();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.KindAttributeImpl <em>Kind Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.KindAttributeImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getKindAttribute()
     * @generated
     */
    EClass KIND_ATTRIBUTE = eINSTANCE.getKindAttribute();

    /**
     * The meta object literal for the '<em><b>Hostgroup</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KIND_ATTRIBUTE__HOSTGROUP = eINSTANCE.getKindAttribute_Hostgroup();

    /**
     * The meta object literal for the '<em><b>Ongroup</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KIND_ATTRIBUTE__ONGROUP = eINSTANCE.getKindAttribute_Ongroup();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KIND_ATTRIBUTE__CONDITION = eINSTANCE.getKindAttribute_Condition();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.TriggerImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Trigger Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__TRIGGER_TYPE = eINSTANCE.getTrigger_TriggerType();

    /**
     * The meta object literal for the '<em><b>Returndef</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__RETURNDEF = eINSTANCE.getTrigger_Returndef();

    /**
     * The meta object literal for the '<em><b>Esig</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__ESIG = eINSTANCE.getTrigger_Esig();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__PARAMS = eINSTANCE.getTrigger_Params();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.JVMTYPEImpl <em>JVMTYPE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.JVMTYPEImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getJVMTYPE()
     * @generated
     */
    EClass JVMTYPE = eINSTANCE.getJVMTYPE();

    /**
     * The meta object literal for the '<em><b>Astk</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JVMTYPE__ASTK = eINSTANCE.getJVMTYPE_Astk();

    /**
     * The meta object literal for the '<em><b>Jvm Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JVMTYPE__JVM_REF = eINSTANCE.getJVMTYPE_JvmRef();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.GroupImpl <em>Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.GroupImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getGroup()
     * @generated
     */
    EClass GROUP = eINSTANCE.getGroup();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUP__NAME = eINSTANCE.getGroup_Name();

    /**
     * The meta object literal for the '<em><b>Hosts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP__HOSTS = eINSTANCE.getGroup_Hosts();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.HostImpl <em>Host</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.HostImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getHost()
     * @generated
     */
    EClass HOST = eINSTANCE.getHost();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOST__IP = eINSTANCE.getHost_Ip();

    /**
     * The meta object literal for the '<em><b>Group Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOST__GROUP_ID = eINSTANCE.getHost_GroupId();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.AutomatonImpl <em>Automaton</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.AutomatonImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getAutomaton()
     * @generated
     */
    EClass AUTOMATON = eINSTANCE.getAutomaton();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTOMATON__NAME = eINSTANCE.getAutomaton_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATON__PARAMS = eINSTANCE.getAutomaton_Params();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTOMATON__STEPS = eINSTANCE.getAutomaton_Steps();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.StepImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__TYPE = eINSTANCE.getStep_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STEP__NAME = eINSTANCE.getStep_Name();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__TRANSITIONS = eINSTANCE.getStep_Transitions();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.TransDefImpl <em>Trans Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.TransDefImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getTransDef()
     * @generated
     */
    EClass TRANS_DEF = eINSTANCE.getTransDef();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANS_DEF__EVENT = eINSTANCE.getTransDef_Event();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANS_DEF__TARGET = eINSTANCE.getTransDef_Target();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.LtlImpl <em>Ltl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.LtlImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtl()
     * @generated
     */
    EClass LTL = eINSTANCE.getLtl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LTL__NAME = eINSTANCE.getLtl_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL__PARAMS = eINSTANCE.getLtl_Params();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL__PREDICATE = eINSTANCE.getLtl_Predicate();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.LtlExpressionImpl <em>Ltl Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.LtlExpressionImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlExpression()
     * @generated
     */
    EClass LTL_EXPRESSION = eINSTANCE.getLtlExpression();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_EXPRESSION__EVENT = eINSTANCE.getLtlExpression_Event();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LTL_EXPRESSION__OP = eINSTANCE.getLtlExpression_Op();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.RcImpl <em>Rc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.RcImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getRc()
     * @generated
     */
    EClass RC = eINSTANCE.getRc();

    /**
     * The meta object literal for the '<em><b>Syncex</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RC__SYNCEX = eINSTANCE.getRc_Syncex();

    /**
     * The meta object literal for the '<em><b>Pos</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RC__POS = eINSTANCE.getRc_Pos();

    /**
     * The meta object literal for the '<em><b>Automaton</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RC__AUTOMATON = eINSTANCE.getRc_Automaton();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RC__STATE = eINSTANCE.getRc_State();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RC__BODY = eINSTANCE.getRc_Body();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.BodyImpl <em>Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.BodyImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getBody()
     * @generated
     */
    EClass BODY = eINSTANCE.getBody();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY__BODY = eINSTANCE.getBody_Body();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.OrEventImpl <em>Or Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.OrEventImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getOrEvent()
     * @generated
     */
    EClass OR_EVENT = eINSTANCE.getOrEvent();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EVENT__LEFT = eINSTANCE.getOrEvent_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EVENT__RIGHT = eINSTANCE.getOrEvent_Right();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.AndEventImpl <em>And Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.AndEventImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getAndEvent()
     * @generated
     */
    EClass AND_EVENT = eINSTANCE.getAndEvent();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EVENT__LEFT = eINSTANCE.getAndEvent_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EVENT__RIGHT = eINSTANCE.getAndEvent_Right();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.UnaryEventImpl <em>Unary Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.UnaryEventImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getUnaryEvent()
     * @generated
     */
    EClass UNARY_EVENT = eINSTANCE.getUnaryEvent();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_EVENT__EXPR = eINSTANCE.getUnaryEvent_Expr();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.LtlThenImpl <em>Ltl Then</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.LtlThenImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlThen()
     * @generated
     */
    EClass LTL_THEN = eINSTANCE.getLtlThen();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_THEN__LEFT = eINSTANCE.getLtlThen_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_THEN__RIGHT = eINSTANCE.getLtlThen_Right();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.LtlOrImpl <em>Ltl Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.LtlOrImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlOr()
     * @generated
     */
    EClass LTL_OR = eINSTANCE.getLtlOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_OR__LEFT = eINSTANCE.getLtlOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_OR__RIGHT = eINSTANCE.getLtlOr_Right();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.LtlAndImpl <em>Ltl And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.LtlAndImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlAnd()
     * @generated
     */
    EClass LTL_AND = eINSTANCE.getLtlAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_AND__LEFT = eINSTANCE.getLtlAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_AND__RIGHT = eINSTANCE.getLtlAnd_Right();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.LtlUntilImpl <em>Ltl Until</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.LtlUntilImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getLtlUntil()
     * @generated
     */
    EClass LTL_UNTIL = eINSTANCE.getLtlUntil();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_UNTIL__LEFT = eINSTANCE.getLtlUntil_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTL_UNTIL__RIGHT = eINSTANCE.getLtlUntil_Right();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.impl.UnaryLtlImpl <em>Unary Ltl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.impl.UnaryLtlImpl
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getUnaryLtl()
     * @generated
     */
    EClass UNARY_LTL = eINSTANCE.getUnaryLtl();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_LTL__EXPR = eINSTANCE.getUnaryLtl_Expr();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.TPrefix <em>TPrefix</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.TPrefix
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getTPrefix()
     * @generated
     */
    EEnum TPREFIX = eINSTANCE.getTPrefix();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.StateType <em>State Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.StateType
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getStateType()
     * @generated
     */
    EEnum STATE_TYPE = eINSTANCE.getStateType();

    /**
     * The meta object literal for the '{@link co.edu.icesi.eketal.eketal.Pos <em>Pos</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.icesi.eketal.eketal.Pos
     * @see co.edu.icesi.eketal.eketal.impl.EketalPackageImpl#getPos()
     * @generated
     */
    EEnum POS = eINSTANCE.getPos();

  }

} //EketalPackage
