/**
 * generated by Xtext 2.9.2
 */
package co.edu.icesi.eketal.eketal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.icesi.eketal.eketal.EventExpression#getTipoEvento <em>Tipo Evento</em>}</li>
 *   <li>{@link co.edu.icesi.eketal.eketal.EventExpression#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getEventExpression()
 * @model
 * @generated
 */
public interface EventExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Tipo Evento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo Evento</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Evento</em>' containment reference.
   * @see #setTipoEvento(EventPredicate)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getEventExpression_TipoEvento()
   * @model containment="true"
   * @generated
   */
  EventPredicate getTipoEvento();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.EventExpression#getTipoEvento <em>Tipo Evento</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Evento</em>' containment reference.
   * @see #getTipoEvento()
   * @generated
   */
  void setTipoEvento(EventPredicate value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getEventExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.EventExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // EventExpression
