/**
 * generated by Xtext 2.10.0
 */
package co.edu.icesi.eketal.eketal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.icesi.eketal.eketal.UnaryEvent#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see co.edu.icesi.eketal.eketal.EketalPackage#getUnaryEvent()
 * @model
 * @generated
 */
public interface UnaryEvent extends EventExpression
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(EventExpression)
   * @see co.edu.icesi.eketal.eketal.EketalPackage#getUnaryEvent_Expr()
   * @model containment="true"
   * @generated
   */
  EventExpression getExpr();

  /**
   * Sets the value of the '{@link co.edu.icesi.eketal.eketal.UnaryEvent#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(EventExpression value);

} // UnaryEvent
