/**
 * generated by Xtext 2.10.0
 */
package co.edu.icesi.eketal.ui;

import co.edu.icesi.eketal.ui.AbstractEketalUiModule;
import co.edu.icesi.eketal.ui.wizard.EketalPluginCreator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EketalUiModule extends AbstractEketalUiModule {
  @Override
  public Class<? extends IProjectCreator> bindIProjectCreator() {
    return EketalPluginCreator.class;
  }
  
  public EketalUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
