#!/bin/sh
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/LICENSE
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-logging/commons-logging
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.commons
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-net
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.httpcomponents/httpcore
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.slf4j/slf4j-api
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.commons/commons-compress
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/co.edu.icesi.eketal
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/com.google.guava
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-io
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.httpcomponents
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.httpcomponents
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.httpcomponents/httpclient
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-lang/commons-lang
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.avro
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.avro/avro
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/co.edu.icesi.eketal/co.edu.icesi.eketal.lib
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/com.google.guava/guava
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-io/commons-io
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.slf4j
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-logging
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.apache.commons/commons-math3
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-net/commons-net
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/commons-lang
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/org.slf4j/slf4j-log4j12
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/hadoop-wordcount
zip -d target/wordcount-hadoop-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/maven/hadoop-wordcount/wordcount-hadoop