/*
 * generated by Xtext 2.10.0
 */
package co.edu.icesi.eketal.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractEketalScopeProvider extends XbaseBatchScopeProvider {
}
