/*
 * generated by Xtext 2.10.0
 */
package co.edu.icesi.eketal.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class EketalWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public EketalWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
